### PR TITLE
Fix ARM Neon dispatch functions handling

### PR DESCRIPTION
**Pull request by RonenGvili**
Latest changes committed to cpu.h and cpu.c overwrote the dispatch logic for the Neon optimized functions, leaving them unused.

### CODE REVIEW

**Comment by RonenGvili** [comment]
HI @ktmf01 . Regarding the changes in cpu.h and cpu.c - notice that the only way to dispatch the 2 Neon function: FLAC__lpc_compute_residual_from_qlp_coefficients_intrin_neon() and FLAC__lpc_compute_residual_from_qlp_coefficients_wide_intrin_neon() in run time is in case of use_asm is true. We do not need arm_cpu_info() function (like the ppc_cpu_info and x86_cpu_info) as it always true. Without this flag using ARM device will dispatch the scalar c code for the lpc_compute_residuals instead of the Neon functions.

**Comment by ktmf01** [comment]
> notice that the only way to dispatch the 2 Neon function [..] in run time is in case of use_asm is true. 

I'll change that as well. Adding dead code doesn't seem like a good idea to me.

**Comment by ktmf01** [comment]
I have made a new PR #336 with the change as I propose it, as this PR is currently not mergeable. Do you agree with that approach?

**Comment by RonenGvili** [comment]
> I have made a new PR #336 with the change as I propose it, as this PR is currently not mergeable. Do you agree with that approach?

I agree.

**Comment by ktmf01** [comment]
Closing this because of the merge of #336 @RonenGvili Thanks for spotting this problem. I only properly tested with autotools, not with cmake. Though, next time you send in a PR, it should be just the commits you want to merge, without a large sum of related (but already merged) commits. If you don't know how to do that, you could search the internet for `git rebase`. Rebasing is letting git apply your changes on top of another branch (usually the master or main branch). You can also 'squash' several commits into a single one with this command.

**Pull request closed without merging**
