### PR TITLE
action.yml: Use config Debug in all cmake steps

### PR DESCRIPTION
**Pull request by c72578**
Use `-DCMAKE_BUILD_TYPE=Debug` and specify `--config Debug` explicitly for
the build.

### CODE REVIEW

**Comment by rillian** [comment]
Thanks for making this consistent. I wasn't sure how to do that.

It looks like this sets `NDEBUG` and therefore turns off assertions. I'd like to have test coverage with those on. What about making it consistently build in debug mode for CI? Or add another matrix dimension and build both Debug and Release, although we already have a long test latency.

**Comment by c72578** [comment]
Thanks for the feedback. I will update the PR and switch to `Debug` in all cmake steps.

**Comment by c72578** [comment]
OK, the PR has been updated to use `Debug`.

**Comment by c72578** [comment]
Info concerning the failed CI build (`macos-latest-clang-cmake-64-bit-words`) [[1]](https://github.com/xiph/flac/pull/250/checks?check_run_id=3194504262):

From log file `build (macos-latest-clang-cmake-64-bit-words)/9_CMake test.txt`:
```console
2021-07-29T17:57:06.1577150Z The following tests FAILED:
2021-07-29T17:57:06.1580180Z 	  8 - streams (Timeout)
```
[1] https://github.com/xiph/flac/pull/250/checks?check_run_id=3194504262

**Comment by ktmf01** [comment]
In #267 I actually set the config to release instead of debug. The problem I had with debug was that the output is so tremendously verbose, the CI fails because the logs grow to several GiB in size.

Can this PR be closed, or am I missing something?

**Comment by c72578** [comment]
Yes, this PR can be closed.

**Pull request closed without merging**
