### PR TITLE
add travis

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by erikd** [comment]
Can you please squash those 3 commits into one?

**Comment by stephengroat** [comment]
no problem, done

**Comment by erikd** [comment]
Thanks @stephengroat

**Comment by erikd** [comment]
@stephengroat I think I'm going to have to remove this travis build thing. There's a number of problems with it:
* Running the FLAC test suite sometimes takes so long that it times out and is killed by travis.
* The FLAC build log is too long and too verbose for the travis "follow log" functionality.

I have my own personal CI (Jenkins on x86_64 with armhf/linux, powerpc/linux and x86_64/darwin build slaves) that I build FLAC in. As such, build in travis serves no real purpose.

**Comment by stephengroat** [comment]
whatever you think is best, i understand. I added it because i've been
noticing that package maintainers are sometimes releasing binaries without
running tests. travis is a nice, reasonably universal system to have an
example script of running tests in the repo and then have a link to look at
the tests and see expected output.

The test suite timing out issue could be solved by splitting it up into
separate builds, i.e. running tests 1-50 in one build and tests 50-100 in
another build. I don't think a long build log is the end of the world,
either. you can always hit the "raw log" button and get the full thing.

the problem with the personal CI is that others can't see the world. You
also tend to get higher quality pull requests with travis and github, since
users can instantaneously get feedback on how their change fits into
current tests

**Pull request closed without merging**
