### PR TITLE
Fix endless loop when skipping link

### PR DESCRIPTION
**Pull request by ktmf01**
Credit: Oss-Fuzz
Issue: N/A (local run)

### CODE REVIEW

**Comment by sezero** [comment]
FYI: The 'distcheck' workflow had a failure in our fork:

```
testing chained-merged.oga:
run_test_seeking chained-merged.oga 100 580716 chained.raw

+++ seek test: FLAC__StreamDecoder (Ogg FLAC, read_mode=0)

stream decoder state is FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC
file's total_samples is 580716
Begin seek barrage, count=100
#0:seek(0)... FAILED, FLAC__stream_decoder_seek_absolute() FAILED, state = 6 (FLAC__STREAM_DECODER_SEEK_ERROR)
ERROR: during test_seeking
make[2]: *** [Makefile:715: check] Error 1
make[2]: Leaving directory '/home/runner/work/flac/flac/flac-1.4.3/_build/sub/test'
make[1]: *** [Makefile:497: check-recursive] Error 1
make[1]: Leaving directory '/home/runner/work/flac/flac/flac-1.4.3/_build/sub'
make: *** [Makefile:713: distcheck] Error 1
Error: Process completed with exit code 2.
```

Full run log: https://github.com/libsdl-org/flac/actions/runs/12094798212/job/33727239452

Don't know whether or not this is a one-off, but reporting just in case.

**Comment by ktmf01** [comment]
Thanks, I'll take a look

**Comment by ktmf01** [comment]
I cannot reproduce currently. It seems reasonable to assume that two streams had the same serial number, this has lead to this error in the past. Such an error would also pop up seldomly because it only happens when the random number generator returns the same number twice. I can't be sure, because the file is already gone of course.

**Comment by sezero** [comment]
Well, it failed again when I sync'ed my fork with current master: https://github.com/sezero/flac/actions/runs/12151771495/job/33886973651

Maybe a difference in OS runner or something? I don't know. But something is definitely going on.

**Comment by ktmf01** [comment]
It is not distcheck this time though. Is the error the same? I cannot view the error, probably not priviledged.

**Comment by sezero** [comment]
> It is not distcheck this time though. Is the error the same? I cannot view the error, probably not priviledged.

Here it is:

```
2024-12-04T02:21:18.1709984Z 8: testing chained-merged.oga:
2024-12-04T02:21:18.1710398Z 8: run_test_seeking chained-merged.oga 100 580716 chained.raw
2024-12-04T02:21:18.1881475Z 8: 
2024-12-04T02:21:18.1881995Z 8: +++ seek test: FLAC__StreamDecoder (Ogg FLAC, read_mode=0)
2024-12-04T02:21:18.1882495Z 8: 
2024-12-04T02:21:18.1882831Z 8: stream decoder state is FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC
2024-12-04T02:21:18.1883284Z 8: file's total_samples is 580716
2024-12-04T02:21:18.1883586Z 8: Begin seek barrage, count=100
2024-12-04T02:21:18.1885613Z 8: #0:seek(0)... FAILED, FLAC__stream_decoder_seek_absolute() FAILED, state = 6 (FLAC__STREAM_DECODER_SEEK_ERROR)
2024-12-04T02:21:18.1887543Z 8: ERROR: during test_seeking
2024-12-04T02:21:18.1892046Z  8/10 Test  #8: seeking ..........................***Failed    0.89 sec
[....]
2024-12-04T02:24:56.7670224Z 
2024-12-04T02:24:56.7670354Z The following tests FAILED:
2024-12-04T02:24:56.7670647Z Errors while running CTest
2024-12-04T02:24:56.7671056Z Output from these tests are in: /home/runner/work/flac/flac/cmake-build/Testing/Temporary/LastTest.log
2024-12-04T02:24:56.7671597Z Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
2024-12-04T02:24:56.7671939Z 	  8 - seeking (Failed)
2024-12-04T02:24:56.7723776Z ##[error]Process completed with exit code 8. 
```

And here is the zip of the full log from the failing run: [log.zip](https://github.com/user-attachments/files/18003673/log.zip)

**Comment by ktmf01** [comment]
@sezero I have been able to reproduce this problem, and #771 should be a proper fix. Thanks for letting me know.

**Pull request merged**
