### PR TITLE
Add missing langinfo check for CMake

### LINKED ISSUE #308: Building with CMake never defines HAVE_LANGINFO_CODESET
Buliding with CMake + Ninja never adds `-DHAVE_LANGINFO_CODESET` to compiler options, so locale detection is not complete in such situation.

Notably, ArchLinux now builds flac with CMake + Ninja (https://github.com/archlinux/svntogit-packages/blob/packages/flac/trunk/PKGBUILD), which causes some locale issue when tagging FLAC files. See: https://github.com/svend/cuetools/issues/38#issuecomment-1082859037

### PR DESCRIPTION
**Pull request by NotTsunami**
Closes #308

### CODE REVIEW

**Comment by NotTsunami** [comment]
Need to fix this check, not ready for merge

**Comment by NotTsunami** [comment]
The test is now passing for Ubuntu. Untested on Arch, but it should fix the issue observed in #308.

**Comment by NotTsunami** [comment]
Small note: for some reason CI is failing on macOS right now, but it seems to be an issue with homebrew and unrelated to the PR

**Comment by ktmf01** [comment]
Yes, I noticed. I'll try triggering a rerun in an hour, if that doesn't work tomorrow

**Pull request merged**
