### PR TITLE
Fix version number display on Windows

### LINKED ISSUE #502: Latest FLAC libs for Windows contain no/wrong version info
Even the libs of the latest release (1.4.2 as of today) are missing version info (please excuse my localized German UI):

`libFLAC.dll`:
image

`libFLAC++.dll`:
image
(This one even hardcoded "1, 0, 0, 0" as product version which is completely wrong, because even in German the version numbers are written as "1.0.0.0" - yet it used the correct, dotted format just 3 lines above as file version (`Dateiversion`)…)

Please, don't fix just the version info, but instead fill all relevant fields with correct data, e. g. copyright, description, (original) name, etc.

### PR DESCRIPTION
**Pull request by ktmf01**
This should fix #502

### CODE REVIEW

**Comment by sezero** [comment]
This doesn't seem to build and link the resources when using autotools.

A crude attempt -- only adding the functionality to libFLAC.dll as an example -- is below.

```diff
diff --git a/configure.ac b/configure.ac
index 5358fa8..da9324b 100644
--- a/configure.ac
+++ b/configure.ac
@@ -39,6 +39,7 @@ AM_PROG_AS
 AC_PROG_CXX
 XIPH_C_COMPILER_IS_CLANG
 XIPH_GCC_REALLY_IS_GCC
+AC_CHECK_TOOL(RC,[windres],[:])
 AC_PROG_MAKE_SET
 AC_PROG_MKDIR_P
 
diff --git a/src/libFLAC/Makefile.am b/src/libFLAC/Makefile.am
index 8ddc13a..43a703a 100644
--- a/src/libFLAC/Makefile.am
+++ b/src/libFLAC/Makefile.am
@@ -64,6 +64,8 @@ EXTRA_DIST = \
 
 if OS_IS_WINDOWS
 windows_unicode_compat = ../share/win_utf8_io/win_utf8_io.c
+libFLAC_la_DEPENDENCIES = version.o
+windows_resource_link = -Wl,version.o
 endif
 
 if FLaC__HAS_OGG
@@ -75,7 +77,7 @@ extra_ogg_sources = \
 endif
 
 # see 'http://www.gnu.org/software/libtool/manual/libtool.html#Libtool-versioning' for numbering convention
-libFLAC_la_LDFLAGS = $(AM_LDFLAGS) -no-undefined -version-info 12:0:0
+libFLAC_la_LDFLAGS = $(AM_LDFLAGS) -no-undefined -version-info 12:0:0 $(windows_resource_link)
 
 libFLAC_sources = \
 	bitmath.c \
@@ -114,3 +116,6 @@ libFLAC_la_SOURCES = $(libFLAC_sources)
 
 # needed for test_libFLAC
 libFLAC_static_la_SOURCES = $(libFLAC_sources)
+
+.rc.o:
+	$(RC) $(AM_CPPFLAGS) $< $@
```

**Comment by ktmf01** [comment]
Thanks! I had tried to get it to work through autotools, but didn't find much documentation. I'll take a look.

**Comment by ktmf01** [comment]
Once more thanks @sezero 

I've augmented your patch a little though. It failed it windres wasn't available. Simply skipping the process seemed a better solution.
```diff
diff --git a/configure.ac b/configure.ac
index 5358fa8f..f9e60db3 100644
--- a/configure.ac
+++ b/configure.ac
@@ -176,10 +176,12 @@ os_is_windows=no
 case "$host" in
        *mingw*)
                os_is_windows=yes
+               AC_CHECK_TOOL(RC,[windres],[:])
                ;;
 esac

 AM_CONDITIONAL(OS_IS_WINDOWS, test "x$os_is_windows" = xyes)
+AM_CONDITIONAL(HAVE_WINDRES, test "x$RC" != "x:")

 case "$host" in
        *-linux-*)
diff --git a/src/libFLAC/Makefile.am b/src/libFLAC/Makefile.am
index 8ddc13ac..57dbc5f0 100644
--- a/src/libFLAC/Makefile.am
+++ b/src/libFLAC/Makefile.am
@@ -66,6 +66,11 @@ if OS_IS_WINDOWS
 windows_unicode_compat = ../share/win_utf8_io/win_utf8_io.c
 endif

+if HAVE_WINDRES
+libFLAC_la_DEPENDENCIES = version.o
+windows_resource_link = -Wl,version.o
+endif
+
 if FLaC__HAS_OGG
 extra_ogg_sources = \
        ogg_decoder_aspect.c \
@@ -75,7 +80,7 @@ extra_ogg_sources = \
 endif

 # see 'http://www.gnu.org/software/libtool/manual/libtool.html#Libtool-versioning' for numbering convention
-libFLAC_la_LDFLAGS = $(AM_LDFLAGS) -no-undefined -version-info 12:0:0
+libFLAC_la_LDFLAGS = $(AM_LDFLAGS) -no-undefined -version-info 12:0:0 $(windows_resource_link)

 libFLAC_sources = \
        bitmath.c \
@@ -114,3 +119,6 @@ libFLAC_la_SOURCES = $(libFLAC_sources)

 # needed for test_libFLAC
 libFLAC_static_la_SOURCES = $(libFLAC_sources)
+
+.rc.o:
+       $(RC) $(AM_CPPFLAGS) $< $@
```

**Comment by sezero** [comment]
> I've augmented your patch a little though. It failed it windres wasn't available. Simply skipping the process seemed a better solution.

OK, I think. (Although, if I have to be picky, I'd move the `if HAVE_WINDRES` block into the `if OS_IS_WINDOWS` block, just in case.)

**Review by sezero — APPROVED** [review]

**Comment by ktmf01** [comment]
@sezero I'd like to mention you as co-author, is that OK?

**Comment by sezero** [comment]
> @sezero I'd like to mention you as co-author, is that OK?

Sure. Thanks.

**Pull request merged**
