### PR TITLE
Prepare FLAC 1.4.3 release

### PR DESCRIPTION
**Pull request by ktmf01**

### CODE REVIEW

**Comment by rillian** [comment]
Packages are now available from the xiph mirrors
- https://downloads.xiph.org/releases/flac/flac-1.4.3.tar.xz
- https://downloads.xiph.org/releases/flac/flac-1.4.3-win.zip

**Comment by petterreinholdtsen** [comment]
[Ralph Giles]
> Packages are now available from the xiph mirrors
> - https://downloads.xiph.org/releases/flac/flac-1.4.3.tar.xz
> - https://downloads.xiph.org/releases/flac/flac-1.4.3-win.zip


Thank you very much for making a new release. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by rillian** [comment]
https://xiph.org/flac/ updated

**Comment by rillian** [comment]
https://xiph.org/downloads/ updated

**Review by bigmatt5469 — COMMENTED** [review]
Yup

**Pull request merged**
