### PR TITLE
make windows dll builds export only the public symbols.

### PR DESCRIPTION
**Pull request by sezero**
this solves https://github.com/xiph/flac/issues/120

This is an initial patch that solves https://github.com/xiph/flac/issues/120
Tested by cross-compiling on linux using autotools and cmake. MSVC
changes need testing.

### CODE REVIEW

**Comment by lvqcl** [comment]
For some reason it breaks encoding of files with non-ASCII filenames:

input filename: RAiNY STARS.wav
output filename: RAiNY STARS.flac

input filename: Иероглиф.wav
output filename: РРµСЂРѕРіР»РёС„.flac

input filename: とびだせ！バンキッキ.wav
output filename: гЃЁгЃігЃ гЃ›пјЃгѓђгѓіг‚­гѓѓг‚­.flac

**Comment by sezero** [comment]
> For some reason it breaks encoding of files with non-ASCII filenames:

I didn't touch any of the code itself.  Did it work fine before?

**Comment by lvqcl** [comment]
Yes, it did work.

windows_unicode_filenames.c contains static variable `utf8_filenames`.

flac.exe calls `get_utf8_argv()`, which in turn calls `flac_set_utf8_filenames()`, which sets this variable to `true`. After this, libFLAC treats filenames as UTF8-encoded.

Maybe currently there are 2 static variables, one in flac.exe and another in libFLAC.dll.

In this case flac.exe changes its own copy, the variable in libFLAC.dll remains unchanged, and libFLAC treats filenames as ANSI-encoded.

**Comment by sezero** [comment]
> windows_unicode_filenames.c contains static variable `utf8_filenames`.
> 
> flac.exe calls `get_utf8_argv()`, which in turn calls `flac_set_utf8_filenames()`, which sets this variable to `true`. After this, libFLAC treats filenames as UTF8-encoded.
> 
> Maybe currently there are 2 static variables, one in flac.exe and another in libFLAC.dll.
> 
> In this case flac.exe changes its own copy, the variable in libFLAC.dll remains unchanged, and libFLAC treats filenames as ANSI-encoded.

Well, I'm stuck there.. Do you have a solution?

**Comment by sezero** [comment]
One solution I can think of is adding a constructor function to dll builds of libFLAC.
Something like:
```
#ifdef FLAC_API_EXPORTS
void __attribute__((constructor)) init_utf8_filenames(void) {
  typedef int (__cdecl *wgetmainargs_t)(int*, wchar_t***, wchar_t***, int, int*);
  wgetmainargs_t wgetmainargs;
  HMODULE handle;

  if ((handle = LoadLibraryW(L"msvcrt.dll")) == NULL) return;
  if ((wgetmainargs = (wgetmainargs_t)GetProcAddress(handle, "__wgetmainargs")) != NULL) {
      flac_set_utf8_filenames(true);
  }
  FreeLibrary(handle);
}
#endif
```

Would this work?  (not tested..)

Yes, get_utf8_argv() in win_utf8_io.c refuses to set utf8_filenames
depending on more failures (such as malloc failure which should 
actually result in an abort itself but whatever), but this should be
enough for a dll if it works.  (and if it works, we'll need an MSVC
equivalent of constructor attribute.)

**Comment by sezero** [comment]
The above seems to work for me (TM).

**Comment by lvqcl** [comment]
TWIMC - the first message about Unicode support for Windows version: http://lists.xiph.org/pipermail/flac-dev/2013-March/003889.html

UTF8 mode was made a runtime choice: http://lists.xiph.org/pipermail/flac-dev/2013-April/003973.html

Basically, the reason why `utf8_filenames` is not `true` by default is: 

> The reason I had them this way is that FLAC API has public functions that work with filenames. Default compile options for FLAC would be unaffected and existing programs that rely on ANSI filenames would continue to work. The new configuration option "Release (UTF-8)" was meant to isolate the changes so that only official bundled frontends that know about the changes would use them.

**Comment by sezero** [comment]
So, what is it that you are proposing?

Should we add a public libFLAC api like `FLAC_set_utf8_filenames(FLAC__bool)`
or something?

**Comment by lvqcl** [comment]
Honestly, I don't know, and I don't care much about it. For me, everything is OK as long as it doesn't break Unicode support.

I also don't care much about FLAC API - it's a mess already... :(

**Comment by sezero** [comment]
OK then.  Well the main idea is here, @erikd should decide what to do.
Or I can can this and let things stay as they are.

**Comment by sezero** [comment]
I did as best as I could, so I'm open to ideas.

**Pull request closed without merging**
