### PR TITLE
fix incorrect usage of realloc in bitwriter_grow_

### PR DESCRIPTION
**Pull request by ltx2018**

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
The patch seem to assume that if realloc() return NULL, the original memory is lost, but the manual page for realloc() at least on Linux state that "If realloc() fails, the original block is left untouched; it is not freed or moved."  The C standard states that "If memory for the new object cannot be allocated, the old object is not deallocated and its value is unchanged.".

This make me believe the proposed change is not correct.

**Comment by ltx2018** [comment]
> The patch seem to assume that if realloc() return NULL, the original memory is lost, but the manual page for realloc() at least on Linux state that "If realloc() fails, the original block is left untouched; it is not freed or moved." The C standard states that "If memory for the new object cannot be allocated, the old object is not deallocated and its value is unchanged.".
> 
> This make me believe the proposed change is not correct.

if realloc() return NULL, original memory will be freed in safe_realloc_
image

**Comment by ltx2018** [comment]
similar to this patch,
in FLAC__stream_decoder_set_metadata_respond_application
image

in read_metadata_seektable_
image

**Comment by ltx2018** [comment]
the problem is 'size1 > SIZE_MAX / size2' in safe_realloc_mul_2op_ , if that happens original memory not freed, so maybe free(ptr) should be called before return.  
any idea?

**Comment by erikd** [comment]
@ltx2018 please do not post screen captures, my screen resolution makes them unreadably small. Instead copy and paste and learn  how to use GH markup.

**Comment by ltx2018** [comment]
> @ltx2018 please do not post screen captures, my screen resolution makes them unreadably small. Instead copy and paste and learn how to use GH markup.

emm..updated

**Comment by ktmf01** [comment]
The problem that the first commit tries to fix appeared today during fuzzing, so it seems this fix is still needed. I will take some time to review it soon.

**Comment by ktmf01** [comment]
This is fixed with the merge of #419

**Pull request closed without merging**
